# Generated by Django 5.1.4 on 2024-12-12 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_user_is_verified_user_verification_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='user',
            name='verification_code',
        ),
    ]
